#!/usr/bin/env bash

process() {
    inicial=$(echo $1 | cut -d '>' -f 1)
    if [[ "$inicial" == workspace || "$inicial" == focusedmon ]]; then
	hyprctl monitors -j | jq '.[] | select(.id == 1) | .activeWorkspace.id'
    fi
}

hyprctl monitors -j | jq '.[] | select(.id == 1) | .activeWorkspace.id'

socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do process "$line" ; done
